#!/usr/bin/env node
//
// One-shot conversion of the "Grundkurs" manuscript into the two formats it
// will live in from now on: LaTeX for the printed book, HTML for the website.
//
// Runs ONCE. After that both outputs are hand-maintained and this file stays
// only as the record of how they came to be - so it has to produce output you
// can edit further, not a scaffold.
//
// Three traps in the source document, all found by measuring rather than
// assuming, all of which corrupt the text silently if you miss them:
//
//   1. Truth tables are COLUMN-MAJOR. A 2x3 table where row 2 holds three
//      cells, each stacking a whole column of values. Read row-wise you get
//      "0 0 1 1 | 0 1 0 1" instead of an AND table. They have to be transposed.
//
//   2. The AND and OR operators are NOT text. They are
//      <w:sym w:font="Symbol" w:char="F0D9"/> and F0DA - Symbol-font private
//      use codepoints. Every naive w:t extraction drops them and leaves
//      "A = E1  E2", which reads as if the operator were a space. 27 of them.
//
//   3. Subscripts are run properties, not characters. Without them every
//      E1/E2 collapses to E1. The document holds 488 w:vertAlign marks, but
//      only 448 belong to text: the other 40 sit in w:pPr/w:rPr, which is the
//      formatting of the paragraph MARK - what the next typed character would
//      get. There is nothing there to carry over, so 448 is the whole of it.
//
// Word also stores its generated matter as ordinary paragraphs - table of
// contents, list of figures, index. Those are dropped and regenerated by
// LaTeX/the site, otherwise the page numbers of 2004 travel along.
//
//   node tools/convert-book.js --check    parse and report, write nothing
//   node tools/convert-book.js            write all outputs

const fs = require("fs")
const path = require("path")
const zlib = require("zlib")

const SRC = process.env.BOOK_SRC
  || path.resolve(__dirname, "../archive/Grundkurs.docx")

const ROOT = path.resolve(__dirname, "..")
const OUT = {
  tex: path.join(ROOT, "print/kapitel"),
  // Der Ingress mountet den Dienst unter /book - das Praefix kommt also
  // von dort. Die Seiten liegen deshalb flach in public/, sonst stuenden sie
  // unter /book/book/.
  html: path.join(ROOT, "book/public"),
  media: path.join(ROOT, "archive/media"),
}

const CHECK = process.argv.includes("--check")

// Dateiname der Druckfassung unter book/public/. print/Makefile erzeugt sie,
// `npm run book:pdf` legt sie hier ab.
const PDF_NAME = "grundkurs-digitaltechnik.pdf"

// What the source is known to contain. A conversion that silently loses half
// the figures still "succeeds" otherwise.
//
// Figures are accounted for rather than just counted: every one of the 72 has
// to end up in a named bucket. Seven of them sit inside layout tables and one
// on the title page, so a plain "did we place 72" would fail forever without
// saying why.
const EXPECT = { chapters: 12, sections: 30, tables: 19, layoutTables: 2, syms: 27, images: 72, subscripts: 448 }

// ---------------------------------------------------------------------------
// A minimal zip reader. docx is a zip; we need three kinds of entry out of it
// and pulling in a dependency for that would be the only dependency this repo
// has.
// ---------------------------------------------------------------------------
function readZip(file) {
  const buf = fs.readFileSync(file)
  let eocd = -1
  for (let i = buf.length - 22; i >= 0 && i > buf.length - 66000; i--) {
    if (buf.readUInt32LE(i) === 0x06054b50) { eocd = i; break }
  }
  if (eocd < 0) throw new Error("kein zip: End-of-Central-Directory nicht gefunden")

  const count = buf.readUInt16LE(eocd + 10)
  let p = buf.readUInt32LE(eocd + 16)
  const entries = new Map()

  for (let n = 0; n < count; n++) {
    if (buf.readUInt32LE(p) !== 0x02014b50) throw new Error("zip-Verzeichnis beschaedigt")
    const method = buf.readUInt16LE(p + 10)
    const nameLen = buf.readUInt16LE(p + 28)
    const extraLen = buf.readUInt16LE(p + 30)
    const commentLen = buf.readUInt16LE(p + 32)
    const localOff = buf.readUInt32LE(p + 42)
    const name = buf.toString("utf8", p + 46, p + 46 + nameLen)
    entries.set(name, { method, localOff })
    p += 46 + nameLen + extraLen + commentLen
  }

  return {
    names: () => [...entries.keys()],
    read(name) {
      const e = entries.get(name)
      if (!e) throw new Error(`nicht im Archiv: ${name}`)
      let q = e.localOff
      if (buf.readUInt32LE(q) !== 0x04034b50) throw new Error("lokaler Header beschaedigt")
      const compSize = buf.readUInt32LE(q + 18)
      const rawSize = buf.readUInt32LE(q + 22)
      q += 30 + buf.readUInt16LE(q + 26) + buf.readUInt16LE(q + 28)
      // Streamed entries put the sizes in a trailing descriptor, so a zero here
      // means "read to the end and let inflate find the boundary".
      const body = buf.subarray(q, compSize ? q + compSize : undefined)
      if (e.method === 0) return body.subarray(0, rawSize || body.length)
      return zlib.inflateRawSync(body)
    },
  }
}

// ---------------------------------------------------------------------------
// Runs and their formatting
// ---------------------------------------------------------------------------

// Symbol font, private use area. Anything not listed here throws rather than
// vanishing - see trap 2 in the header.
const SYMBOL = { F0D9: "\u2227", F0DA: "\u2228" }

const RE = {
  block: /<w:tbl>[\s\S]*?<\/w:tbl>|<w:p\b[^>]*\/>|<w:p\b[\s\S]*?<\/w:p>/g,
  run: /<w:r\b[^>]*>[\s\S]*?<\/w:r>/g,
  // w:t, not w:tabs - the lazy [^>]* form matches both and drags tab markup
  // into the text.
  text: /<w:t(?:\s[^>]*)?>([\s\S]*?)<\/w:t>/g,
  sym: /<w:sym\b[^>]*w:char="([0-9A-Fa-f]+)"[^>]*\/>/g,
  style: /w:pStyle w:val="([^"]+)"/,
  row: /<w:tr\b[\s\S]*?<\/w:tr>/g,
  cell: /<w:tc\b[\s\S]*?<\/w:tc>/g,
  para: /<w:p\b[\s\S]*?<\/w:p>/g,
  image: /<v:imagedata[^>]*r:id="(rId\d+)"/g,
}

function unescapeXml(s) {
  return s.replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"')
          .replace(/&apos;/g, "'").replace(/&amp;/g, "&")
}

let symCount = 0

// A paragraph as a list of formatted runs, in order.
function runsOf(frag) {
  const out = []
  for (const run of frag.match(RE.run) || []) {
    const props = (run.match(/<w:rPr>[\s\S]*?<\/w:rPr>/) || [""])[0]
    const style = {
      sub: /w:vertAlign w:val="subscript"/.test(props),
      sup: /w:vertAlign w:val="superscript"/.test(props),
      b: /<w:b\/>/.test(props),
      i: /<w:i\/>/.test(props),
    }
    // A tab carries no text of its own, but it does separate words. Dropping it
    // glued "E2" to "(sprich:" in every formula.
    let text = /<w:tab\/>/.test(run) ? " " : ""
    for (const m of run.matchAll(RE.text)) text += unescapeXml(m[1])
    for (const m of run.matchAll(RE.sym)) {
      const code = m[1].toUpperCase()
      const ch = SYMBOL[code]
      if (!ch) throw new Error(`unbekanntes Symbolzeichen w:char="${code}" - Zuordnung in SYMBOL ergaenzen`)
      text += ch
      symCount++
    }
    if (text) out.push({ ...style, text })
  }
  return germanQuotes(out)
}

// Word 2004 typed the same character for both ends of a quotation: 123 of the
// 124 quote marks in the manuscript are U+201C. German sets the opening one
// low. Pairing them by alternation within a paragraph is safe here because the
// book never leaves one unclosed.
function germanQuotes(runs) {
  let open = true
  for (const r of runs) {
    if (!r.text.includes("“")) continue
    r.text = r.text.replace(/“/g, () => (open = !open) ? "“" : "„")
  }
  return runs
}

const plain = (runs) => runs.map((r) => r.text).join("").replace(/\s+/g, " ").trim()

// Index entries survive as Word field instructions: XE "Halbaddierer". The
// generated index itself is thrown away with the rest of the generated matter,
// but these markers are the source it was built from, so both outputs can
// regenerate it with their own page numbers.
//
// The instruction is often split across several runs mid-word, so the field has
// to be reassembled before it is read - matching run by run yields fragments of
// XML instead of terms.
function indexTerms(frag) {
  const terms = []
  for (const field of frag.split(/<w:fldChar[^>]*w:fldCharType="begin"[^>]*\/>/).slice(1)) {
    const body = field.split(/<w:fldChar[^>]*w:fldCharType="(?:separate|end)"[^>]*\/>/)[0]
    let instr = ""
    for (const m of body.matchAll(/<w:instrText(?:\s[^>]*)?>([\s\S]*?)<\/w:instrText>/g)) instr += unescapeXml(m[1])
    const xe = instr.match(/^\s*XE\s+"([^"]+)"/)
    if (xe) terms.push(xe[1].trim())
  }
  return terms
}

// ---------------------------------------------------------------------------
// Document tree
// ---------------------------------------------------------------------------

// Word keeps its generated tables as normal paragraphs. Regenerated downstream.
const GENERATED = new Set([
  "Verzeichnis1", "Verzeichnis2", "Verzeichnis3",
  "Abbildungsverzeichnis", "Index1", "Index2", "Indexberschrift",
])

const cellsOf = (row) => (row.match(RE.cell) || [])
// Cells keep their runs. 166 of the 488 subscripts live in table headers, and
// flattening them to text turns every E<sub>1</sub> into "E1".
const parasOf = (cell) => (cell.match(RE.para) || []).map((p) => runsOf(p))
const parasText = (cell) => parasOf(cell).map(plain)

// Not every w:tbl is data. Seven of them are two-column layouts holding a
// circuit diagram on the left and its explanation on the right - the 7490 and
// 7492 divider variants. A figure inside a cell is the reliable tell.
function layoutTable(table, rels) {
  const rows = table.match(RE.row) || []
  const items = []
  for (const row of rows) {
    let figure = null
    const text = []
    for (const cell of cellsOf(row)) {
      const m = [...cell.matchAll(RE.image)].map((x) => rels[x[1]] || "").filter((t) => t.includes("media/"))
      if (m.length) figure = m[0].split("/").pop()
      // Runs, not text: the 7490 prose is full of R<sub>01</sub> and
      // Q<sub>A</sub> pin names.
      for (const runs of parasOf(cell)) if (plain(runs)) text.push(runs)
    }
    if (figure || text.length) items.push({ figure, title: text[0] || null, body: text.slice(1) })
  }
  return items
}

// The book uses two table layouts and they need opposite treatment.
//
//   column-major  header row, then cells that each stack a whole column of
//                 values. Long tables are split into several such rows, each a
//                 further chunk of the same columns - an 8-line truth table
//                 becomes two rows of four. Read row-wise this is nonsense.
//
//   row-major     ordinary table, one value per cell.
//
// The tell is how many paragraphs a body cell holds: more than one means the
// cell is a stacked column.
function dataTable(table) {
  const rows = table.match(RE.row) || []
  if (rows.length < 2) return null

  const head = cellsOf(rows[0]).map((c) => parasOf(c).flat())
  const cellFilled = (c) => parasOf(c).filter((runs) => plain(runs) !== "")

  // A trailing single-cell row ("usw.") is a note, not data - in either layout.
  const dataRows = []
  let note = null
  for (const r of rows.slice(1)) {
    const cells = cellsOf(r)
    if (cells.length === 1 && head.length > 1) {
      const t = parasText(cells[0]).join(" ").trim()
      if (t) note = t
      continue
    }
    dataRows.push(cells)
  }
  if (!dataRows.length) return null

  const columnMajor = cellFilled(dataRows[0][0] ?? "").length > 1
                   || cellFilled(dataRows[0][1] ?? "").length > 1

  const body = []
  if (columnMajor) {
    for (const cells of dataRows) {
      const columns = cells.map(cellFilled)
      const depth = Math.max(0, ...columns.map((c) => c.length))
      for (let i = 0; i < depth; i++) body.push(columns.map((c) => c[i] ?? []))
    }
  } else {
    for (const cells of dataRows) body.push(cells.map((c) => parasOf(c).flat()))
  }

  return { head, body, note, columnMajor }
}

function parse(xml, rels) {
  const body = xml.match(/<w:body>([\s\S]*)<\/w:body>/)[1]
  const blocks = body.match(RE.block) || []

  const doc = []          // chapters, each carrying its own nodes and sections
  let chapter = null
  let section = null

  const counts = { chapters: 0, sections: 0, tables: 0, layoutTables: 0, skipped: 0 }
  // Every one of the 72 figures is assigned a bucket. A plain count would go on
  // reporting "65 of 72" without ever saying where the other seven went.
  const figures = { inText: 0, inLayout: 0, titlePage: 0 }
  const allTerms = new Set()
  // Renaming map for stage 2: image37.wmf -> abb-14. Numbered in document
  // order, which is also the order the reader meets them in.
  const manifest = []
  const number = (source) => {
    manifest.push({ no: manifest.length + 1, source })
    return manifest.length
  }

  const target = () => (section ? section.nodes : chapter ? chapter.nodes : null)
  const mediaIn = (frag) => [...frag.matchAll(RE.image)]
    .map((m) => rels[m[1]] || "").filter((t) => t.includes("media/")).map((t) => t.split("/").pop())

  for (const block of blocks) {
    if (block.startsWith("<w:tbl")) {
      const rows = layoutTable(block, rels)
      const hasFigure = rows.some((r) => r.figure)

      if (hasFigure) {
        // Layout table: diagram left, explanation right. Not data.
        const items = rows.map((r) => (r.figure ? { ...r, no: number(r.figure) } : r))
        figures.inLayout += items.filter((i) => i.figure).length
        if (target()) { target().push({ type: "layout", items }); counts.layoutTables++ }
        continue
      }
      const t = dataTable(block)
      if (t && target()) {
        target().push({ type: "table", ...t })
        counts.tables++
      }
      continue
    }

    const style = (block.match(RE.style) || [])[1] || ""
    if (GENERATED.has(style)) { counts.skipped++; continue }

    const runs = runsOf(block)
    const text = plain(runs)
    const media = mediaIn(block)

    if (style === "berschrift1") {
      if (text === "Inhaltsverzeichnis") { chapter = null; section = null; continue }
      chapter = { type: "chapter", title: text, nodes: [], sections: [] }
      section = null
      doc.push(chapter)
      counts.chapters++
      continue
    }
    if (style === "berschrift2" && chapter) {
      section = { type: "section", title: text, nodes: [] }
      chapter.sections.push(section)
      counts.sections++
      continue
    }

    // Anything before the first chapter is the title page. It carries the cover
    // drawing, which the book sets separately and the website does not use.
    if (!target()) {
      for (const src of media) { number(src); figures.titlePage++ }
      continue
    }

    for (const src of media) {
      target().push({ type: "image", source: src, no: number(src) })
      figures.inText++
    }
    if (!text) continue

    const index = indexTerms(block)
    index.forEach((t) => allTerms.add(t))
    if (style === "Beschriftung") target().push({ type: "caption", text })
    else if (style === "Formel") target().push({ type: "formula", runs, index })
    else target().push({ type: "para", runs, index })
  }

  return { doc, counts, figures, manifest, terms: [...allTerms].sort((a, b) => a.localeCompare(b, "de")) }
}

// ---------------------------------------------------------------------------
// Emitters
// ---------------------------------------------------------------------------

function slug(s) {
  return s.toLowerCase()
    .replace(/\(.*?\)/g, " ")
    .replace(/ä/g, "ae").replace(/ö/g, "oe").replace(/ü/g, "ue").replace(/ß/g, "ss")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
}

const figName = (no) => `abb-${String(no).padStart(2, "0")}`

// Word numbers its own captions ("Tabelle 1:Logiktafel AND-Gatter"). LaTeX and
// the site number their own, so the prefix has to go or every figure ends up
// labelled twice - with the 2004 numbers.
const captionText = (s) => s.replace(/^(Abbildung|Tabelle)\s*\d+\s*:?\s*/i, "").trim()

// A caption is a sibling paragraph following the thing it describes. Hang it on
// that node instead, so the emitters can put it inside the float where LaTeX
// needs it - \caption outside a figure/table environment is an error.
function attachCaptions(nodes) {
  const out = []
  for (const n of nodes) {
    const prev = out[out.length - 1]
    if (n.type === "caption" && prev && (prev.type === "image" || prev.type === "table") && !prev.caption) {
      prev.caption = captionText(n.text)
      continue
    }
    out.push({ ...n })
  }
  return out
}

// --- LaTeX ---

const TEX_ESC = { "\\": "\\textbackslash{}", "&": "\\&", "%": "\\%", "$": "\\$", "#": "\\#",
                  "_": "\\_", "{": "\\{", "}": "\\}", "~": "\\textasciitilde{}", "^": "\\textasciicircum{}" }
// Logic operators via \ensuremath so they typeset in prose and in formulas
// alike, without depending on the text font carrying the glyph.
const TEX_MATH = { "\u2227": "\\ensuremath{\\wedge}", "\u2228": "\\ensuremath{\\vee}", "\u00ac": "\\ensuremath{\\lnot}" }

function tex(s) {
  return s.replace(/[\\&%$#_{}~^]/g, (c) => TEX_ESC[c])
          .replace(/[\u2227\u2228\u00ac]/g, (c) => TEX_MATH[c])
          // „ and “ pass through: lualatex reads Unicode, and flattening them
          // to ASCII would undo the German quotation marks set above.
          .replace(/”/g, "“")
}

function texRuns(runs) {
  return runs.map((r) => {
    let t = tex(r.text)
    if (r.sub) t = `\\textsubscript{${t}}`
    if (r.sup) t = `\\textsuperscript{${t}}`
    if (r.b) t = `\\textbf{${t}}`
    if (r.i) t = `\\emph{${t}}`
    return t
  }).join("")
}

function texNodes(rawNodes, out) {
  for (const n of attachCaptions(rawNodes)) {
    if (n.type === "image") {
      out.push("\\begin{figure}[htbp]", "  \\centering",
               `  \\includegraphics[width=.8\\linewidth]{media/${figName(n.no)}}`)
      if (n.caption) out.push(`  \\caption{${tex(n.caption)}}`)
      out.push("\\end{figure}", "")
      continue
    }
    // A caption with nothing before it is a standalone line, not a float label.
    if (n.type === "caption") { out.push(`\\emph{${tex(captionText(n.text))}}`, ""); continue }
    const idx = (n.index || []).map((t) => `\\index{${tex(t)}}`).join("")
    if (n.type === "para") out.push(texRuns(n.runs) + idx, "")
    else if (n.type === "formula") out.push("\\begin{quote}", `  ${texRuns(n.runs)}`, "\\end{quote}", idx ? idx : "", "")
    else if (n.type === "layout") {
      for (const it of n.items) {
        if (it.title) out.push(`\\subsection*{${texRuns(it.title)}}`, "")
        if (it.figure) {
          out.push("\\begin{figure}[htbp]", "  \\centering",
                   `  \\includegraphics[width=.7\\linewidth]{media/${figName(it.no)}}`,
                   "\\end{figure}", "")
        }
        for (const p of it.body) out.push(texRuns(p), "")
      }
    }
    else if (n.type === "table") {
      const cols = "c".repeat(n.head.length)
      out.push("\\begin{table}[htbp]", "  \\centering")
      if (n.caption) out.push(`  \\caption{${tex(n.caption)}}`)
      out.push(`  \\begin{tabular}{${cols}}`, "    \\toprule",
               `    ${n.head.map(texRuns).join(" & ")} \\\\`, "    \\midrule")
      for (const row of n.body) out.push(`    ${row.map(texRuns).join(" & ")} \\\\`)
      out.push("    \\bottomrule", "  \\end{tabular}")
      if (n.note) out.push(`  \\par\\medskip ${tex(n.note)}`)
      out.push("\\end{table}", "")
    }
  }
}

function emitTex(doc) {
  const files = []
  doc.forEach((ch, i) => {
    const out = [`\\chapter{${tex(ch.title)}}`, ""]
    texNodes(ch.nodes, out)
    for (const s of ch.sections) {
      out.push(`\\section{${tex(s.title)}}`, "")
      texNodes(s.nodes, out)
    }
    files.push({ name: `${String(i + 1).padStart(2, "0")}-${slug(ch.title)}.tex`, body: out.join("\n") })
  })
  return files
}

// --- HTML ---

const htmlEsc = (s) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")

function htmlRuns(runs) {
  return runs.map((r) => {
    let t = htmlEsc(r.text)
    if (r.sub) t = `<sub>${t}</sub>`
    if (r.sup) t = `<sup>${t}</sup>`
    if (r.b) t = `<b>${t}</b>`
    if (r.i) t = `<i>${t}</i>`
    return t
  }).join("")
}

function htmlNodes(rawNodes, out) {
  for (const n of attachCaptions(rawNodes)) {
    if (n.type === "image") {
      const label = htmlEsc(n.caption || "")
      out.push(`      <figure>`, `        <img src="media/${figName(n.no)}.svg" alt="${label}"/>`)
      if (n.caption) out.push(`        <figcaption>${label}</figcaption>`)
      out.push(`      </figure>`)
      continue
    }
    if (n.type === "caption") { out.push(`      <p class="caption">${htmlEsc(captionText(n.text))}</p>`); continue }
    if (n.type === "para") out.push(`      <p>${htmlRuns(n.runs)}</p>`)
    else if (n.type === "formula") out.push(`      <p class="formel">${htmlRuns(n.runs)}</p>`)
    else if (n.type === "layout") {
      for (const it of n.items) {
        if (it.title) out.push(`      <h3>${htmlRuns(it.title)}</h3>`)
        if (it.figure) {
          out.push(`      <figure><img src="media/${figName(it.no)}.svg" alt="${htmlEsc(plain(it.title || []))}"/></figure>`)
        }
        for (const p of it.body) out.push(`      <p>${htmlRuns(p)}</p>`)
      }
    }
    else if (n.type === "table") {
      out.push(`      <table>`)
      if (n.caption) out.push(`        <caption>${htmlEsc(n.caption)}</caption>`)
      out.push(`        <thead><tr>${n.head.map((h) => `<th>${htmlRuns(h)}</th>`).join("")}</tr></thead>`, `        <tbody>`)
      for (const row of n.body) out.push(`          <tr>${row.map((c) => `<td>${htmlRuns(c)}</td>`).join("")}</tr>`)
      out.push(`        </tbody>`, `      </table>`)
      if (n.note) out.push(`      <p class="caption">${htmlEsc(n.note)}</p>`)
    }
  }
}

function firstSentence(nodes) {
  const p = nodes.find((n) => n.type === "para")
  if (!p) return "Digitaltechnik verstehen und im Browser nachbauen."
  const t = plain(p.runs)
  return (t.length > 155 ? t.slice(0, 152).replace(/\s\S*$/, "") + "..." : t)
}

// The table of contents goes into every single page rather than being fetched.
// It costs a couple of kilobytes and buys the thing a book on the web needs
// most: every page linked from every other. Without internal links a crawler
// never reaches the depth of a 31-page work.
//
// `current` gets no link - a page linking to itself is noise.
function tocFor(pages, current) {
  const out = [`    <nav class="toc">`, `      <div class="tocTitle">Grundkurs Digitaltechnik</div>`, `      <ol>`]
  for (const ch of pages.filter((p) => p.kind === "chapter")) {
    const kids = pages.filter((p) => p.kind === "section" && p.parent === ch.slug)
    if (!kids.length) {
      out.push(`        <li>${link(ch, current)}</li>`)
      continue
    }
    // <details> statt eines JavaScript-Aufklappers: das Kapitel laesst sich
    // auch dann oeffnen, wenn das Bundle nicht laedt, und die Tastaturbedienung
    // bringt der Browser mit. Das Kapitel, in dem man gerade liest, steht
    // offen - unabhaengig davon, was gespeichert ist.
    const here = ch.slug === current || kids.some((k) => k.slug === current)
    out.push(`        <li><details data-chapter="${ch.slug}"${here ? " open" : ""}>`)
    out.push(`          <summary>${link(ch, current)}</summary>`)
    out.push(`          <ol>`)
    for (const k of kids) out.push(`            <li>${link(k, current)}</li>`)
    out.push(`          </ol>`)
    out.push(`        </details></li>`)
  }
  out.push(`      </ol>`)
  // Auf jeder Seite, nicht nur auf der Uebersicht: aus der Suche kommt man
  // immer mitten ins Buch, und das Ganze mitzunehmen soll von dort aus keine
  // Rueckwaertsnavigation kosten. Als Karte mit Titelbild, weil ein
  // verschenktes Buch nicht wie eine Fussnote aussehen sollte.
  const chapters = pages.filter((p) => p.kind === "chapter").length
  out.push(`      <a class="bookGift" href="./${PDF_NAME}" download>`)
  out.push(`        <img src="media/cover.jpg" alt="Titelseite: Grundkurs Digitaltechnik" width="120" height="170"/>`)
  out.push(`        <strong>Das ganze Buch als PDF</strong>`)
  out.push(`        <span>${chapters} Kapitel, kostenlos und ohne Anmeldung</span>`)
  out.push(`      </a>`)
  out.push(`    </nav>`)
  return out.join("\n")
}

const link = (p, current) => p.slug === current
  ? `<a class="current" aria-current="page">${htmlEsc(p.title)}</a>`
  : `<a href="./${p.slug}.html">${htmlEsc(p.title)}</a>`

function page({ title, description, slugName, bodyLines, tocMarkup }) {
  return `<!DOCTYPE html>
<html lang="de">

<head>
<meta charset="utf-8"/>
<title>${htmlEsc(title)} - Electra.Academy</title>
<meta name="description" content="${htmlEsc(description)}"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<meta name="robots" content="index, follow"/>

<link rel="canonical" href="https://electra.academy/book/${slugName}.html">
<link rel="icon" type="image/png" href="/common/images/favicon_64x64.png" sizes="64x64"/>
<link rel="icon" type="image/png" href="/common/images/favicon_32x32.png" sizes="32x32"/>

<meta property="og:title" content="${htmlEsc(title)} - Electra.Academy">
<meta property="og:type" content="article">
<meta property="og:url" content="https://electra.academy/book/${slugName}.html">
<meta property="og:description" content="${htmlEsc(description)}">

<link href="/common/css/roboto.css" rel="stylesheet" type="text/css"/>
<link href="/common/css/inter.css" rel="stylesheet" type="text/css"/>
<link href="/common/js/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
<link href="/book/js/webpack/bundle.css" rel="stylesheet" type="text/css"/>

<script src="/common/js/jquery/jquery.js"></script>
<script src="/common/js/bootstrap/js/bootstrap.min.js"></script>

<script type="text/javascript">
  var app = null
  var socket = null
</script>
<!-- The stored theme, applied before the first paint. Contract with
     common/js/theme.js - same storage key, same attribute. -->
<script>try{if(localStorage.getItem("electra.theme")==="modern")document.documentElement.setAttribute("data-theme","modern")}catch(e){}</script>
</head>

<body class="themed bookBody">

<div class="bookLayout">

  <!-- The bar is markup, not JavaScript, the same way the simulator, author and
       designer pages carry it. common/js/AppSwitch and SettingsSwitch append
       themselves into .applicationSwitch. No user menu: reading needs no
       sign-in, and Userinfo would pull in the Google client. -->
  <div class="appbar">
    <a class="brandLink" href="/home/index.html">
      <img class="icon svg" src="/common/images/favicon_64x64.svg" alt="Electra.Academy"/>
    </a>
    <div class="title">
      <h1>Electra.Academy</h1>
      <h2>Grundlagen</h2>
    </div>
    <span class="spacer"></span>
    <span class="group applicationSwitch"></span>
  </div>

  <main>
${tocMarkup}
    <article>
      <h1>${htmlEsc(title)}</h1>
${bodyLines.join("\n")}
    </article>
  </main>

  <!-- Gefuellt von common/js/Footer.js - dieselbe Fusszeile wie auf der
       Startseite und den Rechtsseiten. Sie traegt Impressum und Datenschutz,
       und die gehoeren an EINE Stelle, nicht in eine zweite Abschrift hier. -->
  <div class="footerMount"></div>

</div>
</body>

<script src="/book/js/webpack/bundle.js"></script>
</html>
`
}

// The entry page. It is the one URL the rest of the site links to, so it has to
// state what the book is and then get out of the way of the chapter list.
function overviewPage(pages, terms) {
  const lines = [
    `      <p>Ein vollständiger Grundkurs der Digitaltechnik: vom Dualsystem über die`,
    `         Gatter und ihre Wahrheitstabellen bis zu Flipflops, Zählern, Schieberegistern`,
    `         und dem Volladdierer. Geschrieben von Andreas Herz, ursprünglich als Buch.</p>`,
    `      <p>Jedes Kapitel steht als eigene Seite. Wo es zum Thema eine fertige Schaltung`,
    `         gibt, führt ein Knopf sie direkt im Simulator auf - lesen und ausprobieren`,
    `         am selben Ort.</p>`,
    `      <h2>Inhalt</h2>`,
    `      <ol class="chapterIndex">`,
  ]
  for (const ch of pages.filter((p) => p.kind === "chapter")) {
    lines.push(`        <li><a href="./${ch.slug}.html">${htmlEsc(ch.title)}</a>`)
    const kids = pages.filter((p) => p.kind === "section" && p.parent === ch.slug)
    if (kids.length) {
      lines.push(`          <ul>`)
      for (const k of kids) lines.push(`            <li><a href="./${k.slug}.html">${htmlEsc(k.title)}</a></li>`)
      lines.push(`          </ul>`)
    }
    lines.push(`        </li>`)
  }
  lines.push(`      </ol>`)
  if (terms.length) {
    lines.push(`      <h2>Stichwörter</h2>`,
               `      <p class="stichwoerter">${terms.map(htmlEsc).join(" &middot; ")}</p>`)
  }
  return page({
    title: "Grundkurs Digitaltechnik",
    description: "Digitaltechnik von Grund auf: Dualsystem, Logikgatter, Flipflops, Zähler, "
               + "Schieberegister und Volladdierer - mit Wahrheitstabellen und Schaltungen zum Ausprobieren.",
    slugName: "index",
    bodyLines: lines,
    tocMarkup: tocFor(pages, "index"),
  })
}

function sitemap(pages) {
  const urls = ["", ...pages.map((p) => `${p.slug}.html`)]
    .map((u) => `  <url><loc>https://electra.academy/book/${u}</loc></url>`)
  return `<?xml version="1.0" encoding="UTF-8"?>\n`
       + `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.join("\n")}\n</urlset>\n`
}

function emitHtml(doc) {
  const pages = []
  for (const ch of doc) {
    if (/^Anhang$/i.test(ch.title)) continue

    // "Einführung" is a stub heading, not a topic - it belongs to the chapter.
    const intro = ch.sections.filter((s) => /^Einf/i.test(s.title))
    const topics = ch.sections.filter((s) => !/^Einf/i.test(s.title))

    const chapterNodes = [...ch.nodes, ...intro.flatMap((s) => s.nodes)]
    // A chapter page is written even with no prose of its own, as long as it has
    // topics - otherwise those topic pages have no parent to be reached from,
    // and a page nothing links to is a page Google does not find.
    if (chapterNodes.length || topics.length) {
      const lines = []
      htmlNodes(chapterNodes, lines)
      if (topics.length) {
        lines.push(`      <h2>In diesem Kapitel</h2>`, `      <ul class="chapterIndex">`)
        for (const t of topics) lines.push(`        <li><a href="./${slug(t.title)}.html">${htmlEsc(t.title)}</a></li>`)
        lines.push(`      </ul>`)
      }
      pages.push({ slug: slug(ch.title), title: ch.title,
                   description: firstSentence(chapterNodes), lines, kind: "chapter" })
    }

    for (const t of topics) {
      const lines = []
      htmlNodes(t.nodes, lines)
      pages.push({ slug: slug(t.title), title: t.title,
                   description: firstSentence(t.nodes), lines, kind: "section",
                   parent: slug(ch.title) })
    }
  }
  return pages
}

// ---------------------------------------------------------------------------

function main() {
  const zip = readZip(SRC)
  const xml = zip.read("word/document.xml").toString("utf8")
  const relsXml = zip.read("word/_rels/document.xml.rels").toString("utf8")
  const rels = {}
  for (const m of relsXml.matchAll(/Id="(rId\d+)"[^>]*Target="([^"]+)"/g)) rels[m[1]] = m[2]

  const { doc, counts, figures, manifest, terms } = parse(xml, rels)
  const texFiles = emitTex(doc)
  const pages = emitHtml(doc)

  const inZip = zip.names().filter((n) => n.startsWith("word/media/")).length
  const accounted = figures.inText + figures.inLayout + figures.titlePage

  console.log("Quelle:", SRC, "\n")

  let ok = true
  const check = (label, got, want) => {
    const good = got === want
    if (!good) ok = false
    console.log(`  ${good ? "ok  " : "FEHL"}  ${label.padEnd(22)} ${String(got).padStart(4)} / ${want}`)
  }
  check("Kapitel", counts.chapters, EXPECT.chapters)
  check("Abschnitte", counts.sections, EXPECT.sections)
  check("Wahrheitstabellen", counts.tables, EXPECT.tables)
  check("Layout-Tabellen", counts.layoutTables, EXPECT.layoutTables)
  check("Symbolzeichen", symCount, EXPECT.syms)
  check("Abbildungen zugeordnet", accounted, EXPECT.images)
  check("Abbildungen im Archiv", inZip, EXPECT.images)

  console.log(`\n  Abbildungen nach Fundort:`)
  console.log(`    im Text                ${String(figures.inText).padStart(4)}`)
  console.log(`    in Layout-Tabellen     ${String(figures.inLayout).padStart(4)}`)
  console.log(`    Titelseite (ungenutzt) ${String(figures.titlePage).padStart(4)}`)
  // Counted on the finished tree, not while parsing: table cells are read twice
  // (layout probe, then transpose), so a parse-time counter double-counts.
  const subs = {}
  const bump = (where, runs) => { subs[where] = (subs[where] || 0) + runs.filter((r) => r.sub).length }
  const walk = (nodes) => nodes.forEach((n) => {
    if (n.runs) bump(n.type, n.runs)
    if (n.type === "table") {
      n.head.forEach((h) => bump("table-kopf", h))
      n.body.forEach((r) => r.forEach((c) => bump("table-zellen", c)))
    }
    if (n.type === "layout") n.items.forEach((i) => {
      if (i.title) bump("layout", i.title)
      i.body.forEach((p) => bump("layout", p))
    })
  })
  doc.forEach((ch) => { walk(ch.nodes); ch.sections.forEach((s) => walk(s.nodes)) })
  const subTotal = Object.values(subs).reduce((a, b) => a + b, 0)
  console.log(`\n  Tiefstellungen erhalten: ${subTotal} / ${EXPECT.subscripts}`)
  for (const [k, v] of Object.entries(subs).sort((a, b) => b[1] - a[1])) {
    console.log(`    ${k.padEnd(22)} ${String(v).padStart(4)}`)
  }
  if (subTotal !== EXPECT.subscripts) ok = false
  console.log(`  generierte Verzeichnisabsaetze uebersprungen: ${counts.skipped}`)
  console.log(`\n  LaTeX-Kapiteldateien: ${texFiles.length}`)
  console.log(`  HTML-Seiten:          ${pages.length}`)
  console.log(`\n  ${pages.map((p) => `${p.kind === "chapter" ? "*" : " "} ${p.slug}`).join("\n  ")}`)

  if (!ok) {
    console.log("\nAbweichung gegen den erwarteten Bestand - es geht etwas verloren.")
    process.exit(1)
  }
  if (CHECK) { console.log("\n--check: nichts geschrieben."); return }

  for (const dir of Object.values(OUT)) fs.mkdirSync(dir, { recursive: true })

  for (const f of texFiles) fs.writeFileSync(path.join(OUT.tex, f.name), f.body + "\n")
  for (const p of pages) {
    fs.writeFileSync(path.join(OUT.html, `${p.slug}.html`),
      page({ title: p.title, description: p.description, slugName: p.slug,
             bodyLines: p.lines, tocMarkup: tocFor(pages, p.slug) }))
  }
  fs.writeFileSync(path.join(OUT.html, "index.html"), overviewPage(pages, terms))
  fs.writeFileSync(path.join(OUT.html, "sitemap.xml"), sitemap(pages))
  for (const name of zip.names()) {
    if (!name.startsWith("word/media/")) continue
    fs.writeFileSync(path.join(OUT.media, name.split("/").pop()), zip.read(name))
  }
  // Stage 2 renames by this, so image37.wmf reliably becomes abb-14.
  fs.writeFileSync(path.join(OUT.media, "figures.json"), JSON.stringify(manifest, null, 2) + "\n")

  console.log(`\ngeschrieben nach:\n  ${OUT.tex}\n  ${OUT.html}\n  ${OUT.media}`)
}

main()
